services:
  db:
    image: postgres:15
    container_name: orders_db
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - '5441:5432'
    volumes:
      - orders_data:/var/lib/postgresql/data

  service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: orders_service
    ports:
      - '8007:8000'
      - '9007:9000'
    depends_on:
      - db
    environment:
      - AUTOMIGRATE=true
    command: ["./app", "-conf", "config.yaml"]

volumes:
  orders_data:
