services:
  orders:
    build: .
    container_name: orders
    restart: unless-stopped
    environment:
      - SERVICE_NAME=orders
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - DEBUG=${DEBUG}
      - AUTOMIGRATE=${AUTOMIGRATE}
