// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/orders/v1/models.proto

package orders_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_CREATED   OrderStatus = 0
	OrderStatus_CONFIRMED OrderStatus = 1
	OrderStatus_SHIPPED   OrderStatus = 2
	OrderStatus_ACCEPTED  OrderStatus = 3
	OrderStatus_REJECTED  OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "CREATED",
		1: "CONFIRMED",
		2: "SHIPPED",
		3: "ACCEPTED",
		4: "REJECTED",
	}
	OrderStatus_value = map[string]int32{
		"CREATED":   0,
		"CONFIRMED": 1,
		"SHIPPED":   2,
		"ACCEPTED":  3,
		"REJECTED":  4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orders_v1_models_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_orders_v1_models_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_orders_v1_models_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CounterpartyId int64                  `protobuf:"varint,3,opt,name=counterparty_id,json=counterpartyId,proto3" json:"counterparty_id,omitempty"`
	Status         OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=orders.v1.OrderStatus" json:"status,omitempty"`
	CreatedBy      int64                  `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Items          []*OrderItem           `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_orders_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Order) GetCounterpartyId() int64 {
	if x != nil {
		return x.CounterpartyId
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_CREATED
}

func (x *Order) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_orders_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *OrderItem) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

type OrderSuggestion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductId       int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CurrentQuantity string                 `protobuf:"bytes,2,opt,name=current_quantity,json=currentQuantity,proto3" json:"current_quantity,omitempty"`
	MinQuantity     string                 `protobuf:"bytes,3,opt,name=min_quantity,json=minQuantity,proto3" json:"min_quantity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderSuggestion) Reset() {
	*x = OrderSuggestion{}
	mi := &file_api_orders_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSuggestion) ProtoMessage() {}

func (x *OrderSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSuggestion.ProtoReflect.Descriptor instead.
func (*OrderSuggestion) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *OrderSuggestion) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderSuggestion) GetCurrentQuantity() string {
	if x != nil {
		return x.CurrentQuantity
	}
	return ""
}

func (x *OrderSuggestion) GetMinQuantity() string {
	if x != nil {
		return x.MinQuantity
	}
	return ""
}

var File_api_orders_v1_models_proto protoreflect.FileDescriptor

const file_api_orders_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/orders/v1/models.proto\x12\torders.v1\"\x96\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12'\n" +
	"\x0fcounterparty_id\x18\x03 \x01(\x03R\x0ecounterpartyId\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.orders.v1.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\x03R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12*\n" +
	"\x05items\x18\b \x03(\v2\x14.orders.v1.OrderItemR\x05items\"\x90\x01\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\tR\tunitPrice\"~\n" +
	"\x0fOrderSuggestion\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12)\n" +
	"\x10current_quantity\x18\x02 \x01(\tR\x0fcurrentQuantity\x12!\n" +
	"\fmin_quantity\x18\x03 \x01(\tR\vminQuantity*R\n" +
	"\vOrderStatus\x12\v\n" +
	"\aCREATED\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\v\n" +
	"\aSHIPPED\x10\x02\x12\f\n" +
	"\bACCEPTED\x10\x03\x12\f\n" +
	"\bREJECTED\x10\x04B@Z>github.com/makesalekz/orders/api/orders/v1;orders_v1b\x06proto3"

var (
	file_api_orders_v1_models_proto_rawDescOnce sync.Once
	file_api_orders_v1_models_proto_rawDescData []byte
)

func file_api_orders_v1_models_proto_rawDescGZIP() []byte {
	file_api_orders_v1_models_proto_rawDescOnce.Do(func() {
		file_api_orders_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orders_v1_models_proto_rawDesc), len(file_api_orders_v1_models_proto_rawDesc)))
	})
	return file_api_orders_v1_models_proto_rawDescData
}

var file_api_orders_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_orders_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_orders_v1_models_proto_goTypes = []any{
	(OrderStatus)(0),        // 0: orders.v1.OrderStatus
	(*Order)(nil),           // 1: orders.v1.Order
	(*OrderItem)(nil),       // 2: orders.v1.OrderItem
	(*OrderSuggestion)(nil), // 3: orders.v1.OrderSuggestion
}
var file_api_orders_v1_models_proto_depIdxs = []int32{
	0, // 0: orders.v1.Order.status:type_name -> orders.v1.OrderStatus
	2, // 1: orders.v1.Order.items:type_name -> orders.v1.OrderItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_orders_v1_models_proto_init() }
func file_api_orders_v1_models_proto_init() {
	if File_api_orders_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orders_v1_models_proto_rawDesc), len(file_api_orders_v1_models_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_orders_v1_models_proto_goTypes,
		DependencyIndexes: file_api_orders_v1_models_proto_depIdxs,
		EnumInfos:         file_api_orders_v1_models_proto_enumTypes,
		MessageInfos:      file_api_orders_v1_models_proto_msgTypes,
	}.Build()
	File_api_orders_v1_models_proto = out.File
	file_api_orders_v1_models_proto_goTypes = nil
	file_api_orders_v1_models_proto_depIdxs = nil
}
