// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/orders/v1/orders.proto

package orders_v1

import (
	v1 "github.com/makesalekz/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemRequest) Reset() {
	*x = CreateOrderItemRequest{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemRequest) ProtoMessage() {}

func (x *CreateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderItemRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *CreateOrderItemRequest) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

type CreateOrderRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	CounterpartyId int64                     `protobuf:"varint,1,opt,name=counterparty_id,json=counterpartyId,proto3" json:"counterparty_id,omitempty"`
	Items          []*CreateOrderItemRequest `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetCounterpartyId() int64 {
	if x != nil {
		return x.CounterpartyId
	}
	return 0
}

func (x *CreateOrderRequest) GetItems() []*CreateOrderItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ConfirmOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOrderRequest) Reset() {
	*x = ConfirmOrderRequest{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOrderRequest) ProtoMessage() {}

func (x *ConfirmOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOrderRequest.ProtoReflect.Descriptor instead.
func (*ConfirmOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConfirmOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOrderReply) Reset() {
	*x = ConfirmOrderReply{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOrderReply) ProtoMessage() {}

func (x *ConfirmOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOrderReply.ProtoReflect.Descriptor instead.
func (*ConfirmOrderReply) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmOrderReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ShipOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderRequest) Reset() {
	*x = ShipOrderRequest{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderRequest) ProtoMessage() {}

func (x *ShipOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderRequest.ProtoReflect.Descriptor instead.
func (*ShipOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{7}
}

func (x *ShipOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ShipOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderReply) Reset() {
	*x = ShipOrderReply{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderReply) ProtoMessage() {}

func (x *ShipOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderReply.ProtoReflect.Descriptor instead.
func (*ShipOrderReply) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{8}
}

func (x *ShipOrderReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type AcceptOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{9}
}

func (x *AcceptOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AcceptOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderReply) Reset() {
	*x = AcceptOrderReply{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderReply) ProtoMessage() {}

func (x *AcceptOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderReply.ProtoReflect.Descriptor instead.
func (*AcceptOrderReply) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{10}
}

func (x *AcceptOrderReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type RejectOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectOrderRequest) Reset() {
	*x = RejectOrderRequest{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectOrderRequest) ProtoMessage() {}

func (x *RejectOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectOrderRequest.ProtoReflect.Descriptor instead.
func (*RejectOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{11}
}

func (x *RejectOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RejectOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectOrderReply) Reset() {
	*x = RejectOrderReply{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectOrderReply) ProtoMessage() {}

func (x *RejectOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectOrderReply.ProtoReflect.Descriptor instead.
func (*RejectOrderReply) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{12}
}

func (x *RejectOrderReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderSuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int64                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderSuggestionsRequest) Reset() {
	*x = GetOrderSuggestionsRequest{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderSuggestionsRequest) ProtoMessage() {}

func (x *GetOrderSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderSuggestionsRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

type GetOrderSuggestionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderSuggestion     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderSuggestionsReply) Reset() {
	*x = GetOrderSuggestionsReply{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderSuggestionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderSuggestionsReply) ProtoMessage() {}

func (x *GetOrderSuggestionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderSuggestionsReply.ProtoReflect.Descriptor instead.
func (*GetOrderSuggestionsReply) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrderSuggestionsReply) GetItems() []*OrderSuggestion {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListOrdersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CounterpartyId int64                  `protobuf:"varint,1,opt,name=counterparty_id,json=counterpartyId,proto3" json:"counterparty_id,omitempty"`
	Status         OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=orders.v1.OrderStatus" json:"status,omitempty"`
	FilterStatus   bool                   `protobuf:"varint,3,opt,name=filter_status,json=filterStatus,proto3" json:"filter_status,omitempty"`
	Paginate       *v1.PaginateRequest    `protobuf:"bytes,4,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{15}
}

func (x *ListOrdersRequest) GetCounterpartyId() int64 {
	if x != nil {
		return x.CounterpartyId
	}
	return 0
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_CREATED
}

func (x *ListOrdersRequest) GetFilterStatus() bool {
	if x != nil {
		return x.FilterStatus
	}
	return false
}

func (x *ListOrdersRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type ListOrdersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Order               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReply) Reset() {
	*x = ListOrdersReply{}
	mi := &file_api_orders_v1_orders_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReply) ProtoMessage() {}

func (x *ListOrdersReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_orders_v1_orders_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReply.ProtoReflect.Descriptor instead.
func (*ListOrdersReply) Descriptor() ([]byte, []int) {
	return file_api_orders_v1_orders_proto_rawDescGZIP(), []int{16}
}

func (x *ListOrdersReply) GetItems() []*Order {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListOrdersReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

var File_api_orders_v1_orders_proto protoreflect.FileDescriptor

const file_api_orders_v1_orders_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/orders/v1/orders.proto\x12\torders.v1\x1a\x1aapi/orders/v1/models.proto\x1a\x19api/utils/v1/models.proto\"r\n" +
	"\x16CreateOrderItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\tR\tunitPrice\"v\n" +
	"\x12CreateOrderRequest\x12'\n" +
	"\x0fcounterparty_id\x18\x01 \x01(\x03R\x0ecounterpartyId\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.orders.v1.CreateOrderItemRequestR\x05items\":\n" +
	"\x10CreateOrderReply\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.orders.v1.OrderR\x05order\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"7\n" +
	"\rGetOrderReply\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.orders.v1.OrderR\x05order\"%\n" +
	"\x13ConfirmOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x11ConfirmOrderReply\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.orders.v1.OrderR\x05order\"\"\n" +
	"\x10ShipOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x0eShipOrderReply\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.orders.v1.OrderR\x05order\"$\n" +
	"\x12AcceptOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x10AcceptOrderReply\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.orders.v1.OrderR\x05order\"$\n" +
	"\x12RejectOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x10RejectOrderReply\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.orders.v1.OrderR\x05order\"?\n" +
	"\x1aGetOrderSuggestionsRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x03R\vwarehouseId\"L\n" +
	"\x18GetOrderSuggestionsReply\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.orders.v1.OrderSuggestionR\x05items\"\xc8\x01\n" +
	"\x11ListOrdersRequest\x12'\n" +
	"\x0fcounterparty_id\x18\x01 \x01(\x03R\x0ecounterpartyId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.orders.v1.OrderStatusR\x06status\x12#\n" +
	"\rfilter_status\x18\x03 \x01(\bR\ffilterStatus\x125\n" +
	"\bpaginate\x18\x04 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"n\n" +
	"\x0fListOrdersReply\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.orders.v1.OrderR\x05items\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate2\xf0\x04\n" +
	"\rOrdersService\x12I\n" +
	"\vCreateOrder\x12\x1d.orders.v1.CreateOrderRequest\x1a\x1b.orders.v1.CreateOrderReply\x12@\n" +
	"\bGetOrder\x12\x1a.orders.v1.GetOrderRequest\x1a\x18.orders.v1.GetOrderReply\x12L\n" +
	"\fConfirmOrder\x12\x1e.orders.v1.ConfirmOrderRequest\x1a\x1c.orders.v1.ConfirmOrderReply\x12C\n" +
	"\tShipOrder\x12\x1b.orders.v1.ShipOrderRequest\x1a\x19.orders.v1.ShipOrderReply\x12I\n" +
	"\vAcceptOrder\x12\x1d.orders.v1.AcceptOrderRequest\x1a\x1b.orders.v1.AcceptOrderReply\x12I\n" +
	"\vRejectOrder\x12\x1d.orders.v1.RejectOrderRequest\x1a\x1b.orders.v1.RejectOrderReply\x12a\n" +
	"\x13GetOrderSuggestions\x12%.orders.v1.GetOrderSuggestionsRequest\x1a#.orders.v1.GetOrderSuggestionsReply\x12F\n" +
	"\n" +
	"ListOrders\x12\x1c.orders.v1.ListOrdersRequest\x1a\x1a.orders.v1.ListOrdersReplyB6Z4github.com/makesalekz/orders/api/orders/v1;orders_v1b\x06proto3"

var (
	file_api_orders_v1_orders_proto_rawDescOnce sync.Once
	file_api_orders_v1_orders_proto_rawDescData []byte
)

func file_api_orders_v1_orders_proto_rawDescGZIP() []byte {
	file_api_orders_v1_orders_proto_rawDescOnce.Do(func() {
		file_api_orders_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orders_v1_orders_proto_rawDesc), len(file_api_orders_v1_orders_proto_rawDesc)))
	})
	return file_api_orders_v1_orders_proto_rawDescData
}

var file_api_orders_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_orders_v1_orders_proto_goTypes = []any{
	(*CreateOrderItemRequest)(nil),     // 0: orders.v1.CreateOrderItemRequest
	(*CreateOrderRequest)(nil),         // 1: orders.v1.CreateOrderRequest
	(*CreateOrderReply)(nil),           // 2: orders.v1.CreateOrderReply
	(*GetOrderRequest)(nil),            // 3: orders.v1.GetOrderRequest
	(*GetOrderReply)(nil),              // 4: orders.v1.GetOrderReply
	(*ConfirmOrderRequest)(nil),        // 5: orders.v1.ConfirmOrderRequest
	(*ConfirmOrderReply)(nil),          // 6: orders.v1.ConfirmOrderReply
	(*ShipOrderRequest)(nil),           // 7: orders.v1.ShipOrderRequest
	(*ShipOrderReply)(nil),             // 8: orders.v1.ShipOrderReply
	(*AcceptOrderRequest)(nil),         // 9: orders.v1.AcceptOrderRequest
	(*AcceptOrderReply)(nil),           // 10: orders.v1.AcceptOrderReply
	(*RejectOrderRequest)(nil),         // 11: orders.v1.RejectOrderRequest
	(*RejectOrderReply)(nil),           // 12: orders.v1.RejectOrderReply
	(*GetOrderSuggestionsRequest)(nil), // 13: orders.v1.GetOrderSuggestionsRequest
	(*GetOrderSuggestionsReply)(nil),   // 14: orders.v1.GetOrderSuggestionsReply
	(*ListOrdersRequest)(nil),          // 15: orders.v1.ListOrdersRequest
	(*ListOrdersReply)(nil),            // 16: orders.v1.ListOrdersReply
	(*Order)(nil),                      // 17: orders.v1.Order
	(*OrderSuggestion)(nil),            // 18: orders.v1.OrderSuggestion
	(OrderStatus)(0),                   // 19: orders.v1.OrderStatus
	(*v1.PaginateRequest)(nil),         // 20: utils.v1.PaginateRequest
	(*v1.PaginateReply)(nil),           // 21: utils.v1.PaginateReply
}
var file_api_orders_v1_orders_proto_depIdxs = []int32{
	0,  // 0: orders.v1.CreateOrderRequest.items:type_name -> orders.v1.CreateOrderItemRequest
	17, // 1: orders.v1.CreateOrderReply.order:type_name -> orders.v1.Order
	17, // 2: orders.v1.GetOrderReply.order:type_name -> orders.v1.Order
	17, // 3: orders.v1.ConfirmOrderReply.order:type_name -> orders.v1.Order
	17, // 4: orders.v1.ShipOrderReply.order:type_name -> orders.v1.Order
	17, // 5: orders.v1.AcceptOrderReply.order:type_name -> orders.v1.Order
	17, // 6: orders.v1.RejectOrderReply.order:type_name -> orders.v1.Order
	18, // 7: orders.v1.GetOrderSuggestionsReply.items:type_name -> orders.v1.OrderSuggestion
	19, // 8: orders.v1.ListOrdersRequest.status:type_name -> orders.v1.OrderStatus
	20, // 9: orders.v1.ListOrdersRequest.paginate:type_name -> utils.v1.PaginateRequest
	17, // 10: orders.v1.ListOrdersReply.items:type_name -> orders.v1.Order
	21, // 11: orders.v1.ListOrdersReply.paginate:type_name -> utils.v1.PaginateReply
	1,  // 12: orders.v1.OrdersService.CreateOrder:input_type -> orders.v1.CreateOrderRequest
	3,  // 13: orders.v1.OrdersService.GetOrder:input_type -> orders.v1.GetOrderRequest
	5,  // 14: orders.v1.OrdersService.ConfirmOrder:input_type -> orders.v1.ConfirmOrderRequest
	7,  // 15: orders.v1.OrdersService.ShipOrder:input_type -> orders.v1.ShipOrderRequest
	9,  // 16: orders.v1.OrdersService.AcceptOrder:input_type -> orders.v1.AcceptOrderRequest
	11, // 17: orders.v1.OrdersService.RejectOrder:input_type -> orders.v1.RejectOrderRequest
	13, // 18: orders.v1.OrdersService.GetOrderSuggestions:input_type -> orders.v1.GetOrderSuggestionsRequest
	15, // 19: orders.v1.OrdersService.ListOrders:input_type -> orders.v1.ListOrdersRequest
	2,  // 20: orders.v1.OrdersService.CreateOrder:output_type -> orders.v1.CreateOrderReply
	4,  // 21: orders.v1.OrdersService.GetOrder:output_type -> orders.v1.GetOrderReply
	6,  // 22: orders.v1.OrdersService.ConfirmOrder:output_type -> orders.v1.ConfirmOrderReply
	8,  // 23: orders.v1.OrdersService.ShipOrder:output_type -> orders.v1.ShipOrderReply
	10, // 24: orders.v1.OrdersService.AcceptOrder:output_type -> orders.v1.AcceptOrderReply
	12, // 25: orders.v1.OrdersService.RejectOrder:output_type -> orders.v1.RejectOrderReply
	14, // 26: orders.v1.OrdersService.GetOrderSuggestions:output_type -> orders.v1.GetOrderSuggestionsReply
	16, // 27: orders.v1.OrdersService.ListOrders:output_type -> orders.v1.ListOrdersReply
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_orders_v1_orders_proto_init() }
func file_api_orders_v1_orders_proto_init() {
	if File_api_orders_v1_orders_proto != nil {
		return
	}
	file_api_orders_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orders_v1_orders_proto_rawDesc), len(file_api_orders_v1_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_orders_v1_orders_proto_goTypes,
		DependencyIndexes: file_api_orders_v1_orders_proto_depIdxs,
		MessageInfos:      file_api_orders_v1_orders_proto_msgTypes,
	}.Build()
	File_api_orders_v1_orders_proto = out.File
	file_api_orders_v1_orders_proto_goTypes = nil
	file_api_orders_v1_orders_proto_depIdxs = nil
}
