// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/makesalekz/orders/internal/biz"
	"github.com/makesalekz/orders/internal/conf"
	"github.com/makesalekz/orders/internal/data"
	"github.com/makesalekz/orders/internal/server"
	"github.com/makesalekz/orders/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	ordersRepo := data.NewOrdersRepo(dataData)
	conn, cleanup2, err := data.NewNatsClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	orderConfirmedPublisher := data.NewOrderConfirmedPublisher(conn, logger)
	ordersUsecase := biz.NewOrdersUsecase(logger, ordersRepo, orderConfirmedPublisher)
	ordersService := service.NewOrdersService(ordersUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, ordersService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
